### ISSUE TITLE
XPath.name and XPath::HTML.name should follow Ruby conventions

### ISSUE THREAD

**Issue by betesh** [teamcapybara/xpath#76]
The [mutant gem](https://github.com/mbj/mutant), and other code tools, depend on each class defining a singleton_method called `name` that returns a String or nil. XPath and XPath::HTML don't follow that convention.

See mbj/mutant#338 and the tickets referenced from there for more details.

In particular, see sparklemotion/nokogiri#1635, which I mistakenly opened thinking that this issue was coming from nokogiri when in reality it was coming from xpath.

I am using xpath 2.0.0 (indirectly--it's a dependency of capybara which I am using).

**Comment by twalpole** [comment]
@jnicklas Any thoughts on this?  Possibly renaming it to `qname` or something like that?  Obviously it would be a breaking change (along with the XPath::HTML removal) and would probably be best to have a deprecation release first.

**Comment by twalpole** [comment]
@jnicklas  FYI - I don't believe the method is used in Capybara.
