### ISSUE TITLE
Next release

### ISSUE THREAD

**Issue by twalpole** [teamcapybara/xpath#85]
@jnicklas  How do you feel about a new release of the `xpath` gem?  Would be nice to get a release that has the `contains-word` function in it for Capybara 3 to depend on.

**Comment by twalpole** [comment]
Sounds good to me -- if there were any other breaking changes you were thinking of now would be the time 😄

**Comment by twalpole** [comment]
ruby 2.2+ only perhaps?

**Comment by twalpole** [comment]
@jnicklas Any other changes you can think of that should delay a 3.0 release?

**Comment by jnicklas** [comment]
Sorry for the delay, I think we should be good to go on this one. Do you want me to create the release or do you want to do it yourself?

**Comment by twalpole** [comment]
@jnicklas Doesn't matter to me.  If you have time to create the release please do so, otherwise I'll probably get to it beginning of next week.

**Comment by jnicklas** [comment]
Pushed out a v3 release.
