### ISSUE TITLE
Parenthesis for (union) precedence

### ISSUE THREAD

**Issue by Tails** [teamcapybara/xpath#89]
I'm trying to generate a union path and to then prepend a root path. However, this results in the union operator not getting precedence and therefore either needing parenthesis or the root path to be prepended twice (for both unionised paths). I would prefer to be able to do this without having to prepend the root path twice to the union paths.

````
      path = XPath::Union.new(
        x.child(:a),
        x.child(:b)
      )

      XPath.descendant(:root).descendant(path)
````

Expected result: ````//root(//a | //b)````
Actual result: ````//root//a | b````

Is there a way for this to be done without resorting to string manipulation?

Edit: ofcourse there's also the added problem that parenthesis are not valid after a // path: https://stackoverflow.com/a/6140161

**Comment by jnicklas** [comment]
The xpath gem only targets the version 1 of the XPath spec. I think `//root(//a | //b)` may be valid in XPath2, I'm not too familiar with that spec, but it definitely is not valid in XPath1. Even if it were, it probably wouldn't do what you want it to, you'd probably want something like `//root(.//a | .//b)`.

The xpath gem does not allow expressions to be arbitrarily composed, instead what is happening in your code above is that anything not known to XPath including its own expressions is treated as a literal, so `to_s` is called on it and it's printed right into the expression.

You actually could have written the above expression like this:

``` ruby
XPath.descendant(:root).child(:a, :b)
```

Or if you have a more complex selector, you can write it like this:

``` ruby
root = XPath.descendant(:root)
root.child(:a).union(root.child(:b))

# or this if you're using v3 of the xpath gem
root.child(:a) + root.child(:b)
```
